services:
  rutorrent-ui:
    image: nginx:alpine
    container_name: rutorrent-ui

    ports:
      - "8080:80"

    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/upstream.conf:/etc/nginx/conf.d/default.conf:ro

    command: >
      /bin/sh -c "
      if [ ! -f /usr/share/nginx/html/index.html ]; then
        wget -O /usr/share/nginx/html/index.html \
          https://raw.githubusercontent.com/thevickypedia/RuTorrent/main/src/templates/index.html;
      fi &&
      nginx -g 'daemon off;'
      "

    restart: unless-stopped
