services:
  rutorrent-ui:
    image: nginx:alpine
    container_name: rutorrent-ui

    ports:
      - "${RUTORRENT_WEBUI_PORT:-8000}:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/upstream.conf:/etc/nginx/conf.d/default.conf:ro

    restart: unless-stopped
